import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NextLayout from "@/app/provider";
import ReactQueryProvider from "@/app/react-query-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Mini Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}>
        <ReactQueryProvider>
          <NextLayout>{children}</NextLayout>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
